### ISSUE TITLE
Error when creating new project

### ISSUE THREAD

**Issue by noorbakerally** [BRACKETS-by-TRIAD/craftable#344]
I just install craftable and I am not able to create a new project. This is following error i am getting:

```
craftable new fbapp

PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\Process::isTtySupported() in /root/.config/composer/vendor/brackets/craftable-installer/src/Command.php:30
Stack trace:
#0 /root/.config/composer/vendor/brackets/craftable-installer/src/NewCommand.php(55): Brackets\CraftableInstaller\Console\Command->runCommand('composer create...')
#1 /root/.config/composer/vendor/symfony/console/Command/Command.php(255): Brackets\CraftableInstaller\Console\NewCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /root/.config/composer/vendor/symfony/console/Application.php(992): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /root/.config/composer/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Brackets\CraftableInstaller\Console\NewCommand), Object(Symfony\Component\Consol in /root/.config/composer/vendor/brackets/craftable-installer/src/Command.php on line 30

```

**Comment by palypster** [comment]
Cannot reproduce, sorry
