### ISSUE TITLE
Unable to locate Mix file

### ISSUE THREAD

**Issue by mustafaabduljalil** [BRACKETS-by-TRIAD/craftable#356]
Unable to locate Mix file: /css/admin.css. (View: /var/www/html/adcarft/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php)

**Comment by GonrasK** [comment]
same here. after running 'npm run dev' - the admin management broke down

**Comment by GonrasK** [comment]
<img width="816" alt="Screen Shot 2021-08-16 at 12 04 49" src="https://user-images.githubusercontent.com/30444072/129539468-62d86f2e-4465-4568-a662-5eff1652dc30.png">

getting bunch of these errors after trying to 'npm run dev'.. i tried to 'composer update', but it still didn't help

**Comment by GonrasK** [comment]
Getting bunch of these errors when trying to 'npm run dev'. I tried to 'composer update' first, but it still didn't help..
```

ERROR in ./resources/js/admin/admin.js 2:0-54
Module not found: Error: Can't resolve 'vue-multiselect/dist/vue-multiselect.min.css' in '/Users/gonrs/project/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 3:0-48
Module not found: Error: Can't resolve 'vue-flatpickr-component' in '/Users/gonrs/project/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 4:0-46
Module not found: Error: Can't resolve 'vue-quill-editor' in '/Users/gonrs/project/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 5:0-45
Module not found: Error: Can't resolve 'vue-notification' in '/Users/gonrs/project/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 6:0-42
Module not found: Error: Can't resolve 'vue-multiselect' in '/Users/gonrs/project/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 7:0-39
Module not found: Error: Can't resolve 'vee-validate' in '/Users/gonrs/project/resources/js/admin'
```

**Comment by wowthemesnet** [comment]
Solution for me was 

`npm update vue-loader`

and then 

`npm install && npm run dev`

**Comment by GonrasK** [comment]
> Solution for me was
> 
> `npm update vue-loader`
> 
> and then
> 
> `npm install && npm run dev`

didn't help me.. when i ran ```npm update vue-loader``` , it just said 'up to date' and didn't do anything..

**Comment by GonrasK** [comment]
anyone? please?... everytime i try to `npm run dev` or even `npm run watch`, i get A LOT of errors... what happened all of a sudden?

here's the full error dump -

```
> watch
> npm run development -- --watch


> development
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"


✖ Mix
  Compiled with some errors in 7.03s


● Mix █████████████████████████ done (99%)  
 plugins

WARNING in ./node_modules/craftable/index.js 6:0-54
export 'default' (reexported as 'Auth') was not found in './assets/js/auth/Form' (module has no exports)

WARNING in ./node_modules/craftable/index.js 7:0-73
export 'default' (reexported as 'TranslationForm') was not found in './assets/js/translation/Form' (module has no exports)

WARNING in ./node_modules/craftable/index.js 8:0-79
export 'default' (reexported as 'TranslationListing') was not found in './assets/js/translation/Listing' (module has no exports)

ERROR in ./resources/js/admin/admin.js 2:0-54
Module not found: Error: Can't resolve 'vue-multiselect/dist/vue-multiselect.min.css' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 3:0-48
Module not found: Error: Can't resolve 'vue-flatpickr-component' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 4:0-46
Module not found: Error: Can't resolve 'vue-quill-editor' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 5:0-45
Module not found: Error: Can't resolve 'vue-notification' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 6:0-42
Module not found: Error: Can't resolve 'vue-multiselect' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 7:0-39
Module not found: Error: Can't resolve 'vee-validate' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 8:0-38
Module not found: Error: Can't resolve 'flatpickr/dist/flatpickr.css' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 9:0-35
Module not found: Error: Can't resolve 'vue-cookie' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 11:0-34
Module not found: Error: Can't resolve 'vue-js-modal' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 12:0-22
Module not found: Error: Can't resolve 'vue' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/admin.js 15:0-27
Module not found: Error: Can't resolve 'craftable/dist/ui' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/bootstrap.js 3:0-22
Module not found: Error: Can't resolve 'vue' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/bootstrap.js 4:0-28
Module not found: Error: Can't resolve 'jquery' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./resources/js/admin/bootstrap.js 5:0-28
Module not found: Error: Can't resolve 'moment' in '/Users/gonras/projectX/resources/js/admin'

ERROR in ./node_modules/craftable/assets/js/auth/Form.js 1:0-22
Module not found: Error: Can't resolve 'vue' in '/Users/gonras/projectX/node_modules/craftable/assets/js/auth'

ERROR in ./node_modules/craftable/assets/js/base-components/Form/BaseForm.js 61:55-105
Module not found: Error: Can't resolve 'flatpickr/dist/l10n' in '/Users/gonras/projectX/node_modules/craftable/assets/js/base-components/Form'

ERROR in ./node_modules/craftable/assets/js/base-components/Form/BaseUpload.js 1:0-37
Module not found: Error: Can't resolve 'vue2-dropzone' in '/Users/gonras/projectX/node_modules/craftable/assets/js/base-components/Form'

ERROR in ./node_modules/craftable/assets/js/base-components/Listing/BaseListing.js 1:0-28
Module not found: Error: Can't resolve 'moment' in '/Users/gonras/projectX/node_modules/craftable/assets/js/base-components/Listing'

ERROR in ./node_modules/craftable/assets/js/translation/Form.js 1:0-22
Module not found: Error: Can't resolve 'vue' in '/Users/gonras/projectX/node_modules/craftable/assets/js/translation'

ERROR in ./node_modules/craftable/assets/js/translation/Listing.js 1:0-22
Module not found: Error: Can't resolve 'vue' in '/Users/gonras/projectX/node_modules/craftable/assets/js/translation'

ERROR in ./resources/sass/admin/admin.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ @import "~craftable/scss/app";
  │         ^^^^^^^^^^^^^^^^^^^^^
  ╵
  resources/sass/admin/vendor/_index.scss 2:9  @import
  /Users/gonras/projectX/resources/sass/admin/admin.scss 5:9                                    root stylesheet
    at processResult (/Users/gonras/projectX/node_modules/webpack/lib/NormalModule.js:713:19)
    at /Users/gonras/projectX/node_modules/webpack/lib/NormalModule.js:819:5
    at /Users/gonras/projectX/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/gonras/projectX/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/gonras/projectX/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/gonras/projectX/node_modules/sass-loader/dist/index.js:73:7
    at Function.call$2 (/Users/gonras/projectX/node_modules/sass/sass.dart.js:
● Mix █████████████████████████ cache (99%)  
 store build dependencies
```

**Comment by GonrasK** [comment]
And after I try one of these commands - my whole admin is basically getting broken.. 

```
Exception
Unable to locate Mix file: /css/admin.css. (View: /Users/gonras/projectX/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php)
https://projectx.test/admin/products/create
```

**Comment by RichardDominik** [comment]
@GonrasK Hello, please try to remove `node_modules` folder and `package-lock.json` file. Then try to run `npm install` and `npm run dev`. In case of any error please provide us the whole terminal output. Also please send us node and npm version in case you are not using Laravel Sail. Thanks.

**Comment by GonrasK** [comment]
First of all - `npm install` resulted in 4 vulnerabilities (2 moderate, 2 high), and when i `npm audit` - I get this info - 

```
axios  <=0.21.0
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
Denial of Service - https://npmjs.com/advisories/880
fix available via `npm audit fix`
node_modules/craftable/node_modules/axios
  craftable  >=1.0.1
  Depends on vulnerable versions of axios
  Depends on vulnerable versions of vue-quill-editor
  node_modules/craftable

quill  *
Severity: moderate
Cross-Site Scripting - https://npmjs.com/advisories/1695
fix available via `npm audit fix`
node_modules/quill
  vue-quill-editor  *
  Depends on vulnerable versions of quill
  node_modules/vue-quill-editor
    craftable  >=1.0.1
    Depends on vulnerable versions of axios
    Depends on vulnerable versions of vue-quill-editor
    node_modules/craftable

4 vulnerabilities (2 moderate, 2 high)
```

and when running `npm run dev`, I get this error - 

```
ERROR in ./resources/js/admin/admin.js 15:0-27
Module not found: Error: Can't resolve 'craftable/dist/ui' in '/Users/websites/projectx/resources/js/admin'

ERROR in ./resources/sass/admin/admin.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ @import "~craftable/scss/app";
  │         ^^^^^^^^^^^^^^^^^^^^^
  ╵
  resources/sass/admin/vendor/_index.scss 2:9  @import
  /Users/websites/projectx/resources/sass/admin/admin.scss 5:9                                    root stylesheet
    at processResult (/Users/websites/projectx/node_modules/webpack/lib/NormalModule.js:721:19)
    at /Users/websites/projectx/node_modules/webpack/lib/NormalModule.js:827:5
    at /Users/websites/projectx/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/websites/projectx/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/websites/projectx/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/websites/projectx/node_modules/sass-loader/dist/index.js:73:7
    at Function.call$2 (/Users/websites/projectx/node_modules/sass/sass.dart.js:94122:16)
    at _render_closure1.call$2 (/Users/websites/projectx/node_modules/sass/sass.dart.js:82377:12)
    at _RootZone.runBinary$3$3 (/Users/websites/projectx/node_modules/sass/sass.dart.js:27674:18)
    at _FutureListener.handleError$1 (/Users/websites/projectx/node_modules/sass/sass.dart.js:26223:19)

ERROR in ./node_modules/vue-quill-editor/src/editor.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <div class="quill-editor">
|     <slot name="toolbar"></slot>

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 4 errors
```

**Comment by GonrasK** [comment]
Forgot to mention node and npm version.

```
gonras:projectx gonras$ node -v
v14.15.1
gonras:projectx gonras$ npm -v
7.20.3
```

**Comment by ginkgomzd** [comment]
I don't really understand what is going on here, but I'm no npm expert. A StackExchange post led me to a bug in npm that was closed ten years ago:
https://github.com/npm/npm/issues/1341#issuecomment-20634338

However, the symptoms seem to match.

Running `> sail npm ls -a` shows unmet dependencies for craftable.

The resolution appears to be to run 
`> sail npm install craftable`

**Comment by GonrasK** [comment]
@RichardDominik @palypster ? This problem still persists... Would really love to get support on this one.

and @ginkgomzd - i dont use sail.

**Comment by RichardDominik** [comment]
@GonrasK Hey, I cannot reproduce the reported issue. I tried to create a new Craftable project using Sail and also without Sail (with Node.js and npm installed locally on my macOS).  Based on the error you provided in the last comment I think that is related to this issue https://github.com/BRACKETS-by-TRIAD/craftable/issues/308. So please look at the answers in the mentioned issue.

**Comment by ginkgomzd** [comment]
@GonrasK , looks to me like `npm install craftable` did resolve this issue and you are now facing the other issue Richard linked to.

@RichardDominik my read of the npm problem is that caching makes it hard to reproduce. Once the package is properly retrieved with all dependencies, you won't be able to reproduce it.

I'm really not sure about the specific circumstance that caused it. I installed craftable and used it fine one day. When I resumed work, the problem came up.  I think I did several things with npm but since I wasn't aware of the issue yet, I did not take note.

One possibility is that I ran `npm audit fix`. I don't think this had anything to do with npm versions since I did observe it both with the sail distro version of npm as well as with the latest version. 

I also wish I had noted better: but I think that at one point npm downgraded the craftable version, I think likely that was by running `npm audit fix`.

I've got a busy couple of days, but if you are unable to reproduce, I'll give it another try a little later.

**Comment by stanleyvarga** [comment]
@GonrasK Can you please provide output of your `webpack.mix.js`? Since the error originated in node_modules I guess you might have skipped calling `.vue()` loader in your webpack config file. 

The error happened when you tried to include a vue library which does not include compiled `.js` files or you referenced the source file itself.

So if you find `.vue()` missing from your `webpack.mix.js` file, try to install it first by running `npm install -D vue-loader` and use it like this:

```js
// webpack.mix.js
mix
  .js(["resources/js/admin/admin.js"], "public/js")
  .vue() // <--- include me
  .sass("resources/sass/admin/admin.scss", "public/css")
```

I hope this will help with your problem

**Comment by GonrasK** [comment]
unfortunately nothing worked for me, as you can see i opened another issue for that - https://github.com/BRACKETS-by-TRIAD/craftable/issues/373 ..

i am interested in your premium product but with all these bugs every week - its very hard to trust a tool with so little testing
