### ISSUE TITLE
Error in npm run dev

### ISSUE THREAD

**Issue by Faizanq** [BRACKETS-by-TRIAD/craftable#58]
ERROR in ./node_modules/craftable/coreui/img/correct.png
Module build failed: Error: spawn /home/machine/Desktop/AP/testing/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
 @ ./node_modules/css-loader??ref--9-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--9-4!./node_modules/sass-loader/lib/loader.js??ref--9-5!./resources/assets/admin/scss/app.scss 7:351505-351573 7:358553-358621 7:375983-376051
 @ ./resources/assets/admin/scss/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/admin/scss/app.scss

ERROR in ./node_modules/craftable/coreui/img/error.png
Module build failed: Error: spawn /home/machine/Desktop/AP/testing/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
 @ ./node_modules/css-loader??ref--9-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--9-4!./node_modules/sass-loader/lib/loader.js??ref--9-5!./resources/assets/admin/scss/app.scss 7:351651-351717 7:358702-358768 7:375828-375894
 @ ./resources/assets/admin/scss/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/admin/scss/app.scss

ERROR in ./node_modules/craftable/coreui/img/lock.png
Module build failed: Error: spawn /home/machine/Desktop/AP/testing/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
 @ ./node_modules/css-loader??ref--9-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--9-4!./node_modules/sass-loader/lib/loader.js??ref--9-5!./resources/assets/admin/scss/app.scss 7:352702-352767
 @ ./resources/assets/admin/scss/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/admin/scss/app.scss

ERROR in ./node_modules/craftable/coreui/img/envelope.png
Module build failed: Error: spawn /home/machine/Desktop/AP/testing/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
 @ ./node_modules/css-loader??ref--9-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--9-4!./node_modules/sass-loader/lib/loader.js??ref--9-5!./resources/assets/admin/scss/app.scss 7:352545-352614
 @ ./resources/assets/admin/scss/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/admin/scss/app.scss

ERROR in ./node_modules/craftable/coreui/img/error-triangle.png
Module build failed: Error: spawn /home/machine/Desktop/AP/testing/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
 @ ./node_modules/css-loader??ref--9-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--9-4!./node_modules/sass-loader/lib/loader.js??ref--9-5!./resources/assets/admin/scss/app.scss 7:379588-379663
 @ ./resources/assets/admin/scss/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/admin/scss/app.scss

ERROR in ./resources/assets/admin/scss/app.scss
Module build failed: ModuleBuildError: Module build failed: Error: spawn /home/machine/Desktop/AP/testing/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at runLoaders (/home/machine/Desktop/AP/testing/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/machine/Desktop/AP/testing/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/machine/Desktop/AP/testing/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/machine/Desktop/AP/testing/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/machine/Desktop/AP/testing/node_modules/img-loader/index.js:45:31
    at <anonymous>
 @ ./resources/assets/admin/scss/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/admin/scss/app.scss

ERROR in ./resources/assets/admin/js/profile-edit-password/Form.js
Module not found: Error: Can't resolve '../components/Form/AppForm' in '/home/machine/Desktop/AP/testing/resources/assets/admin/js/profile-edit-password'
 @ ./resources/assets/admin/js/profile-edit-password/Form.js 1:0-49
 @ ./resources/assets/admin/js/profile-edit-password/index.js
 @ ./resources/assets/admin/js/index.js
 @ ./resources/assets/admin/js/admin.js
 @ multi ./resources/assets/admin/js/admin.js

ERROR in ./resources/assets/admin/js/profile-edit-profile/Form.js
Module not found: Error: Can't resolve '../components/Form/AppForm' in '/home/machine/Desktop/AP/testing/resources/assets/admin/js/profile-edit-profile'
 @ ./resources/assets/admin/js/profile-edit-profile/Form.js 1:0-49
 @ ./resources/assets/admin/js/profile-edit-profile/index.js
 @ ./resources/assets/admin/js/index.js
 @ ./resources/assets/admin/js/admin.js
 @ multi ./resources/assets/admin/js/admin.js

ERROR in ./resources/assets/admin/js/user/Form.js
Module not found: Error: Can't resolve '../components/Form/AppForm' in '/home/machine/Desktop/AP/testing/resources/assets/admin/js/user'
 @ ./resources/assets/admin/js/user/Form.js 1:0-49
 @ ./resources/assets/admin/js/user/index.js
 @ ./resources/assets/admin/js/index.js
 @ ./resources/assets/admin/js/admin.js
 @ multi ./resources/assets/admin/js/admin.js

ERROR in ./resources/assets/admin/js/user/Listing.js
Module not found: Error: Can't resolve '../components/Listing/AppListing' in '/home/machine/Desktop/AP/testing/resources/assets/admin/js/user'
 @ ./resources/assets/admin/js/user/Listing.js 1:0-58
 @ ./resources/assets/admin/js/user/index.js
 @ ./resources/assets/admin/js/index.js
 @ ./resources/assets/admin/js/admin.js
 @ multi ./resources/assets/admin/js/admin.js

Additionally I have installed [npm install --save craftable] but didnt solved the error

**Comment by Faizanq** [comment]
Solved by running
$ npm rebuild mozjpeg
$ npm rebuild gifsicle
$ npm rebuild optipng-bin
